services:
  db:
    image: 'postgres:16.3-alpine'
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=myuser
    ports:
      - '5432:5432'
    volumes:
      - app_db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d mydatabase -U myuser" ]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    build: .
    ports:
      - '8080:8080'
    depends_on:
      db:
        condition: service_healthy
volumes:
  app_db:
