services:
  db:
    image: 'postgres:16.2-alpine'
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=myuser
    ports:
      - '5432:5432'
    volumes:
        - app_db:/var/lib/postgresql/data
volumes:
  app_db:
